{% set name = "lpynn" %}
{% set version = "0.0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lpynn-{{ version }}.tar.gz
  sha256: 5e2a4ce7203c19c0f17a47952aefd05096497e4cda12f0a8849bae405acd0e3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lpython_emulation

test:
  imports:
    - lpynn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Shaikh-Ubaid/lpython_packages
  summary: A basic neural networks python package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shaikh-Ubaid
