{% set name = "lpynn" %}
{% set version = "0.0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lpynn-{{ version }}.tar.gz
  sha256: 2e70fc4b8c59330f4b0b1d8c4c26e96343fa93cc52b1e31201d4553e959ce490

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lpython_emulation

test:
  imports:
    - lpynn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Shaikh-Ubaid/lpython_packages
  summary: A basic neural networks python package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shaikh-Ubaid
